config/routes.rb
Rails.application.routes.draw do

  root to: 'posts#index'
  resources :posts, only: [:new, :edit, :create, :edit, :update]
  
  resources :users, only: [:new, :edit, :show ]

  resources :sessions, only: [:new ]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :item
  mount_uploader :image, ImageUploader
end
#imageのところはsrcもあり？

app/models/item.rb
class Item < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index 
    @items = Item.all
  end

  def new 
    @item = Item.new
  end

  def create
    Item.create(item_params)
  end

  def edit
    #@item = Item.find(params[:id])
  end

  def update
    item = Item.find(params[:id])
    item.update(tweet_params)

  end

  def item_params
    params.require(:item).permit(:name, :image, :text, :category)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new  
    @user = User.new
  end

  def edit

  end

  def show

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Cookture
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render "posts/header"
    = yield
    = render "posts/footer"

app/views/posts/_body.html.haml
.mainPage
  .genreList
    .genreName
      %p Pasta
      %p Pizza
      %p Salad
      %p A la carte
      %p Other
  .genreList__contents
    .genreList__content
      .genreList__content__picture コンテンツ写真<!縦に５品まで、それ以上はページ遷移>
      .genreList__content__text 
        %p レシピ
        %p レシピ
        %p レシピ
      .genreList__content__edit 編集ボタン

app/views/posts/_btn.html.haml
= link_to "/posts/new", class: "post__btn" do
  投稿

app/views/posts/_footer.html.haml
.footer
  .footer-contents
    = link_to "/", class: "title" do
      .mainTitle Cookture
      .subTitle ~料理の画像投稿サイト~
    .text 料理の画像とレシピを投稿しよう!
    

app/views/posts/_header.html.haml
.header 
  .header-contents
    = link_to "/", class: "title" do
      .mainTitle Cookture
      .subTitle ~料理の画像投稿サイト~
    .genres
      = link_to "", class: "pasta" do
        Pasta
      = link_to "", class: "pizza" do
        Pizza
      = link_to "", class: "salad" do
        Salad
      = link_to "", class: "alacarte" do
        A la carte
      = link_to "", class: "other" do
        Other
    = link_to "/sessions/new", class: "logIn__btn" do
      ログイン
    = link_to "/users/new", class: "signUp__btn" do
      新規登録

app/views/posts/_main_body.html.haml
.mainPage
  .genreList
    .genres
      = link_to "", class: "pasta" do
        Pasta
      = link_to "", class: "pizza" do
        Pizza
      = link_to "", class: "salad" do
        Salad
      = link_to "", class: "alacarte" do
        A la carte
      = link_to "", class: "other" do
        Other
  - @items.each do |item|
    = render @messages
  = link_to "/posts/:id/edit", class: "edit__btn" do
    編集する

app/views/posts/create.html.haml
.body
  .text 投稿できました！
  = link_to "/", class: "backBtn" do
    トップページへ戻る

app/views/posts/edit.html.haml
.editPage
  .editPage__contents
    .title
      編集ページ
    = form_with local: true do |f|
      .image
        .imageName 料理画像
        .imageName__box
          = f.file_field :image, class: "imageName__box__input"
      .menu
        .menuName メニュー名
        .menuName__box
          = f.text_field :name, class: "menuName__box__input"
      .genre 
        .genreName ジャンル名
        .genreName__box
          = f.text_field :category, class: "genreName__box__input"
      .recipe 
        .recipeContents レシピ内容
        .recipe__box
          = f.text_area :text, class: "recipe__box__input"
      .editBtn
        = f.submit "編集", class: "postBtn__submit"

app/views/posts/index.html.haml
.wrapper
  = render'posts/btn'
  = render'posts/main_body'

app/views/posts/new.html.haml
.postPage
  .postPage__title
    新規投稿ページ
  .postPage__contents
    = form_with local: true do |f|
      .image
        .imageName 料理画像
        .imageName__box
          = f.file_field :image, class: "imageName__box__input"
      .menu
        .menuName メニュー名
        .menuName__box
          = f.text_field :name, class: "menuName__box__input"
      .genre 
        .genreName ジャンル名
        .genreName__box
          = f.text_field :category, class: "genreName__box__input"
      .recipe 
        .recipeContents レシピ内容
        .recipe__box
          = f.text_area :text, class: "recipe__box__input"
      .postBtn
        = f.submit "投稿", class: "postBtn__submit"

        //5行目= form_with model: @item, local: true do |f|？

app/views/posts/update.html.haml
.updatePage
  .text 編集できました！
  = link_to "/", class: "backBtn" do
    トップページへ戻る

app/views/users/edit.html.haml
.logIn
  .contents ログインページ

app/views/users/new.html.haml
.signUp__page 
  .title
    新規登録画面
  .textBox
    = form_with model: @user, url: new_user_url, local: true do |f|
      .nickname
        .nickname__text ニックネーム
        .nickname__box
          = f.text_field :nickname, class: "nickname__box__input"
      .email 
        .email__text メールアドレス
        .email__box
          = f.text_field :email, class: "email__box__input"
      .password 
        .password__text パスワード
        .password__box
          = f.text_field :password, class: "password__box__input"
      .signUp__btn
        = f.submit "登録", class: "signUp__btn__submit"


        //deviseでビュー作成しなくてはならない？

app/views/users/show.html.haml
.mypage
  .title
    マイページ
  .user_contents
    .userInfo
      .userInfo_title
        ユーザー情報
      .nickname
        nickname
      .email
        email
      = link_to "/", class: "userInfo__editBtn" do
        編集する
    .postInfo
      投稿履歴
    = link_to "/posts/:id/edit", class: "editBtn" do
      編集する
    = link_to "/", class: "deleteBtn" do
      削除する